nodeLinker: node-modules

# В Yarn v4 вместо unsafeYarnDependencies и pnpMode используется эта команда.
# Она отключает строгое падение из-за несовпадения версий FontAwesome.
logFilters:
  - code: YN0060